### PR TITLE
Properly read empty objects

### PR DESCRIPTION
**Pull request by FrogTheFrog**
Hello,

so my "shortcuts.vdf" has a lot of backspace characters after an empty "tags" property. The problem is that the main regex does not match them and `m` variable is null. This produces and error which can be avoided in two ways:

1. Break out of `do{}while` loop. Technically, if the regex does not match, there are no more properties.
2. Check `m` for `null`.

I choose the second solution, because I noticed `input.i` incrementation after the loop. Furthermore, I put the main regex outside of the `do{}while` loop, because there really is no need to recreate it (maybe it will save a milisecond or so...).

**Edit:**
Haven't properly read your code before writing this, so both solution basically are one and the same :/ . Still leaving original unedited for context.

### CODE REVIEW

**Comment by FrogTheFrog** [comment]
It seems that parser fails to properly read vdf file which was saved by steam. This might be the real problem. Closing until parsing problem is resolved.

**Comment by FrogTheFrog** [comment]
Parser is unable to read empty "tags" array.

**Comment by FrogTheFrog** [comment]
It seems that parser failed to read empty object properly, some minor changes and this parser works like a charm :)

**Comment by tirish** [comment]
Oh nice, thanks @FrogTheFrog ! Mind if I change the base branch of PR to a temporary branch so I make some tweaks to this?

**Comment by FrogTheFrog** [comment]
Sure, go ahead.

**Comment by tirish** [comment]
@FrogTheFrog, just curious, what OS were you using to generate those shortcut files?

**Comment by FrogTheFrog** [comment]
@tirish, so far just Windows 10, but I will test it on Ubuntu in a week or so. Will notify you if it works so you can add it to readme.

**Comment by tirish** [comment]
@FrogTheFrog awesome, thank you! see my PR that introduces your fix: https://github.com/tirish/steam-shortcut-editor/issues/6

**Pull request merged**
